# Generated by Django 5.2 on 2025-04-26 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_waterlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterlevel',
            name='sensor_data',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='water_levels', to='Dashboard.sensordata'),
            preserve_default=False,
        ),
    ]
