# Generated by Django 5.2 on 2025-04-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_waterlevel_sensor_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
