# Generated by Django 5.1.6 on 2025-04-02 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialMediaPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("facebook", "Facebook"), ("instagram", "Instagram")],
                        max_length=20,
                    ),
                ),
                ("post_id", models.CharField(max_length=255, unique=True)),
                ("message", models.TextField()),
                ("created_time", models.DateTimeField()),
                ("source", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SocialMediaComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_id", models.CharField(max_length=255, unique=True)),
                ("text", models.TextField()),
                ("created_time", models.DateTimeField()),
                ("username", models.CharField(max_length=255)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="sentiment.socialmediapost",
                    ),
                ),
            ],
        ),
    ]
