# Generated by Django 5.1.6 on 2025-04-04 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sentiment", "0002_alter_socialmediacomment_created_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_type", models.CharField(max_length=50)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SentimentAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("post", "Post"), ("comment", "Comment")],
                        max_length=10,
                    ),
                ),
                ("object_id", models.CharField(max_length=255)),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.FloatField()),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="socialmediacomment",
            name="sentiment",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="socialmediacomment",
            name="translated_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="sentiment",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="translated_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sentiment_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sentiment.sentimentanalysisresult",
                    ),
                ),
            ],
        ),
    ]
