# Generated by Django 5.1.6 on 2025-04-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sentiment", "0004_remove_sentimentanalysisresult_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediapost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="attachments/"),
        ),
    ]
