# Generated by Django 5.1.6 on 2025-04-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sentiment", "0006_postlike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediacomment",
            name="comment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
