# Generated by Django 5.1.6 on 2025-04-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sentiment", "0007_alter_socialmediacomment_comment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediapost",
            name="post_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
