# Generated by Django 5.1.6 on 2025-04-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sentiment", "0008_alter_socialmediapost_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediapost",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
