"""empty message

Revision ID: d1f39a8e0a90
Revises: 493fbf11ad78
Create Date: 2025-03-25 20:56:30.550532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f39a8e0a90'
down_revision = '493fbf11ad78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unknown_faces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unknown_faces', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
