# Generated by Django 5.1.6 on 2025-04-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detection", "0002_alter_history_user_alter_setting_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accidentpronearea",
            name="accient_prone",
            field=models.BooleanField(default=False),
        ),
    ]
