# Generated by Django 5.1.6 on 2025-04-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detection", "0004_rename_accient_prone_accidentpronearea_accident_prone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="area",
        ),
        migrations.AddField(
            model_name="alert",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
