# Generated by Django 5.1.6 on 2025-04-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detection", "0005_remove_alert_area_alert_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="destination",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="start",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
