# Generated by Django 5.1.6 on 2025-04-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detection", "0007_journey"),
    ]

    operations = [
        migrations.AddField(
            model_name="journey",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Start", "Start"),
                    ("Arrived", "Arrived"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
