# Generated by Django 5.1.6 on 2025-04-26 15:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detection", "0008_journey_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SafetyNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
        ),
    ]
