# Generated by Django 5.1.6 on 2025-04-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("Basic User", "Basic User")],
                default="Basic User",
                help_text="Role of the user",
                max_length=10,
            ),
        ),
    ]
