# Generated by Django 5.1.6 on 2025-02-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("Gate Man", "Gate Man")],
                default="Admin",
                max_length=10,
            ),
        ),
    ]
