# Generated by Django 5.1.6 on 2025-04-23 12:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
