# Generated by Django 5.1.6 on 2025-04-23 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_about_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="about",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
