# Generated by Django 5.1.6 on 2025-04-23 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("detection", "0003_accidentpronearea_accient_prone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accidentpronearea",
            old_name="accient_prone",
            new_name="accident_prone",
        ),
    ]
