# Generated by Django 5.1.6 on 2025-02-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("officer", "Officer"),
                    ("reporter", "Reporter"),
                ],
                default="admin",
                max_length=10,
            ),
        ),
    ]
