# Generated by Django 5.1.6 on 2025-04-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="language",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
