// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdGP2z3elc2wAkDUHl9g3s33iCMYvw1QA',
    appId: '1:43145049298:web:5477c57219e440af7ce90b',
    messagingSenderId: '43145049298',
    projectId: 'drai-ecaf7',
    authDomain: 'drai-ecaf7.firebaseapp.com',
    storageBucket: 'drai-ecaf7.firebasestorage.app',
    measurementId: 'G-C1WLVM3RE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdGP2z3elc2wAkDUHl9g3s33iCMYvw1QA', // Using web API key as fallback
    appId: '1:43145049298:android:YOUR_ANDROID_ID', // You'll need the correct Android appId
    messagingSenderId: '43145049298',
    projectId: 'drai-ecaf7',
    storageBucket: 'drai-ecaf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdGP2z3elc2wAkDUHl9g3s33iCMYvw1QA', // Using web API key as fallback
    appId: '1:43145049298:ios:YOUR_IOS_ID', // You'll need the correct iOS appId
    messagingSenderId: '43145049298',
    projectId: 'drai-ecaf7',
    storageBucket: 'drai-ecaf7.firebasestorage.app',
    iosBundleId: 'com.example.drAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdGP2z3elc2wAkDUHl9g3s33iCMYvw1QA', // Using web API key as fallback
    appId: '1:43145049298:macos:YOUR_MACOS_ID', // You'll need the correct macOS appId
    messagingSenderId: '43145049298',
    projectId: 'drai-ecaf7',
    storageBucket: 'drai-ecaf7.firebasestorage.app',
    iosBundleId: 'com.example.drAi.RunnerTests',
  );
}