# Generated by Django 5.2 on 2025-05-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_user_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_scan',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
