# Generated by Django 5.2 on 2025-05-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_user_last_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='violation_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
