name: Emergency Medical Services

publish_to: 'none'


environment:
  sdk: '>=3.2.1 <4.0.0'


dependencies:
  animated_bottom_navigation_bar: ^1.3.0
  file_picker: any #^6.2.0
  bloc: ^8.1.2
  build_runner: ^2.4.11
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.13.3
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  share_plus: ^7.2.1
  cross_file: ^0.3.4
  dropdown_button2: ^2.3.6
  easy_stepper: ^0.8.3
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_facebook_auth: ^6.0.4
  flutter_polyline_points: ^2.0.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  formatted_text: ^4.0.1
  gap: ^3.0.1
  geolocator: ^11.0.0
  google_generative_ai: ^0.4.3
  google_maps_flutter: ^2.5.3
  google_sign_in: ^6.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  image_picker: ^1.0.4
  intl: ^0.19.0
  loading_indicator: ^3.1.1
  location: ^6.0.1
  lottie: ^2.4.0
  material_floating_search_bar_2: ^0.5.0
  meta: ^1.10.0
  modal_progress_hud_nsn: ^0.5.1
  path_provider: ^2.1.3
  shared_preferences: ^2.2.2
  sign_in_with_apple: ^6.1.0
  speech_to_text: 7.0.0
  url_launcher: ^6.2.4
  uuid: ^4.2.1


dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
